### ISSUE TITLE
docs: Github Issue Template, PR Template 추가

### ISSUE THREAD

**Issue by Do-hyun-Kim** [YAPP-Github/WeSpot-iOS#1]
## 개요
- Github 협업 시 필요한 Issue Template, PR Template 추가 

## 기능 이름
- 코딩 컨벤션 논의 한 대로 Issue Template, PR Template을 추가 하겠습니다.

**Comment by agseou** [comment]
확인했습니다!
제니 수고하셨습니다 :)
